---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: document
  path: index.html
  label: INDEX
- type: document
  path: _data/translations.yml
  label: Translations
  match: "**/*"
- type: directory
  path: en/_posts
  label: EN_POSTS
  create: documents
  match: "**/*"
- type: directory
  path: es/_posts
  label: ES_POSTS
  create: all
  match: "**/*"
- type: directory
  path: en
  label: EN_PAGES
  create: documents
  match: "*.md"
  exclude: _posts/
- type: directory
  path: es
  label: ES_PAGES
  create: documents
  match: "*.md"
  exclude: _posts/
- type: directory
  path: _layouts
  label: layouts
  create: all
  match: "**/*"
  new_doc_ext: "*.*"
upload_dir: assets/images
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
